/*
 * main.c
 * 
 * DO NOT EDIT THIS FILE
 * 
 * This file is the entry point for unit tests.
 * 
 */
 
#include "test_search.h"

int main(int argc, char** argv) {
    /*
     * just call run_munit_tests
     *
     */
    return run_munit_tests(argc, argv); 
}
