# make file for the factorial project
# DO NOT EDIT THIS FILE
CC ?= cc
APP=search

TEST=test_$(APP)
MAIN=main

BIN_DIR=bin
MAIN_C=$(MAIN).c
MAIN_BIN=$(BIN_DIR)/$(MAIN)

APP_C=$(APP).c
APP_SRC=$(APP_C) $(APP).h
APP_O=$(BIN_DIR)/$(APP).o

MUNIT_C=munit.c
MUNIT_SRC=$(MUNIT_C) munit.h
MUNIT_O=$(BIN_DIR)/munit.o

TEST_C=$(TEST).c
TEST_SRC=$(TEST_C) $(TEST).h 
TEST_O=$(BIN_DIR)/$(TEST).o

all: main
.PHONY: all

run: main
	$(MAIN_BIN)
.PHONY: run

main: $(MAIN_BIN)
.PHONY: main

clean: clean_o clean_a_out clean_core clean_bin
.PHONY: clean

$(MAIN_BIN): $(MAIN_C) $(TEST_O) $(APP_O) $(MUNIT_O)
	$(CC) -Wall $(CFLAGS) $(MAIN_C) $(TEST_O) $(APP_O) $(MUNIT_O) -o $@
   
$(TEST_O): $(TEST_SRC) $(BIN_DIR) 
	$(CC) -Wall $(CFLAGS) -c $(TEST_C) -o $@
	
$(APP_O): $(APP_SRC) $(BIN_DIR) 
	$(CC) -Wall $(CFLAGS) -c $(APP_C) -o $@

$(MUNIT_O): $(MUNIT_SRC) $(BIN_DIR) 
	$(CC) -Wall $(CFLAGS) -c $(MUNIT_C) -o $@

$(BIN_DIR):
	test -d $(BIN_DIR) || mkdir $(BIN_DIR)
	
clean_bin:
	-rm -rf $(BIN_DIR)
.PHONY: clean_bin
	
clean_core:
	-rm -f ./core.*
	-rm -f $(BIN_DIR)/core.*
.PHONY: clean_core
    
clean_o:
	-rm -f *.o
	-rm -f $(BIN_DIR)/*.o
.PHONY: clean_o

clean_a_out:
	-rm -f a.out
	-rm -f $(BIN_DIR)/a.out
.PHONY: clean_a_out