/* 
 * test_search.h - structures and function declarations for unit tests
 * of search functions.
 * 
 * DO NOT EDIT THIS FILE.
 */  
#ifndef _TEST_SEARCH_H
#define _TEST_SEARCH_H
#define MUNIT_ENABLE_ASSERT_ALIASES
#include "munit.h"

/* known entry point to run all unit tests */
int run_munit_tests(int argc, char** argv);

MunitResult test_linearsearch(const MunitParameter params[], void* fixture);
MunitResult test_rlinearsearch(const MunitParameter params[], void* fixture);
MunitResult test_slinearsearch(const MunitParameter params[], void* fixture);
MunitResult test_binarysearch(const MunitParameter params[], void* fixture);
MunitResult test_rbinarysearch(const MunitParameter params[], void* fixture);

static MunitTest tests[] = {
    { "/test_linearsearch", test_linearsearch, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_rlinearsearch", test_rlinearsearch, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_slinearsearch", test_slinearsearch, NULL, NULL, 
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_binarysearch", test_binarysearch, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { "/test_rbinarysearch", test_rbinarysearch, NULL, NULL,
        MUNIT_TEST_OPTION_NONE, NULL },
    { NULL, NULL, NULL, NULL, MUNIT_TEST_OPTION_NONE, NULL},
};

static const MunitSuite suite = {
    "/test_search", tests, NULL, 1, MUNIT_SUITE_OPTION_NONE 
};    


#endif